apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
spec:
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      labels:
        app: datadog-agent
    spec:
      containers:
        - name: agent
          image: datadog/agent:latest
          env:
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_APM_ENABLED
              value: "true"
          volumeMounts:
            - name: datadog-config
              mountPath: /etc/datadog-agent/conf.d/python.d
            - name: allowed-log-path
              mountPath: /var/log/datadog
        - name: trace-agent
          image: datadog/agent:latest
          volumeMounts:
            - name: allowed-log-path
              mountPath: /var/log/datadog
        - name: process-agent
          image: datadog/agent:latest
          volumeMounts:
            - name: allowed-log-path
              mountPath: /var/log/datadog
      volumes:
        - name: allowed-log-path
          emptyDir: {}  # Use emptyDir instead of hostPath
        - name: datadog-config
          configMap:
            name: datadog-config
