apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-reco-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: games-reco-test
  template:
    metadata:
      labels:
        app: games-reco-test
    spec:
      containers:
      - name: games-reco-test
        image: us-central1-docker.pkg.dev/ayoba-183a7/gcf-artifacts/games-reco-test:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: gcp-sa-key
          mountPath: /var/secrets/google
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
      volumes:
      - name: gcp-sa-key
        secret:
          secretName: gcp-sa-key
