apiVersion: v1
kind: Service
metadata:
  name: games-reco-test-service
spec:
  selector:
    app: games-reco-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5009
  type: LoadBalancer
