apiVersion: v1
kind: Service
metadata:
  name: games-recom-test-service
spec:
  selector:
    app: games-recom-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
