datadog:
  apiKey: 
    valueFrom:
      secretKeyRef:
        name: datadog-secret
        key: api-key
  appKey: 
    valueFrom:
      secretKeyRef:
        name: datadog-secret
        key: app-key
  site: "app.datadoghq.com"

  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    containerCollectUsingVolumes: true

  apm:
    enabled: true 
    portEnabled: true
    env: "production"

  dogstatsd:
    enabled: true
    nonLocalTraffic: true
    port: 8125

  agent:
    env:
      - name: DD_LOGS_INJECTION
        value: "true"
      - name: DD_APM_ENABLED
        value: "true"
