datadog:
  apiKey: 
    valueFrom:
      secretKeyRef:
        name: datadog-secret
        key: api-key
  appKey: 
    valueFrom:
      secretKeyRef:
        name: datadog-secret
        key: app-key
  site: "app.datadoghq.com"

  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    containerCollectUsingVolumes: true

  apm:
    enabled: true 
    portEnabled: false  # Disable host port usage
    env: "production"

  dogstatsd:
    enabled: true
    nonLocalTraffic: true

  agent:
    image:
      repository: "gcr.io/datadoghq/agent"
      tag: "7.31.1"
    env:
      - name: DD_LOGS_INJECTION
        value: "true"
      - name: DD_APM_ENABLED
        value: "true"
    volumeMounts:
      - name: datadog-config
        mountPath: /etc/datadog-agent/conf.d/python.d
      - name: allowed-log-path
        mountPath: /var/log/datadog
    volumes:
      - name: datadog-config
        configMap:
          name: datadog-config
      - name: allowed-log-path
        hostPath:
          path: /var/log/datadog

  daemonset:
    useHostPID: false  # Ensure hostPID is disabled
    useHostPort: false  # Avoid using host ports

  agents:
    trace:
      enabled: true
      port: 8126  # Ensure this port is not bound to the host
    process:
      enabled: true
      port: 8126  # Ensure this port is not bound to the host
