datadog:
  apiKey: 
    valueFrom:
      secretKeyRef:
        name: datadog-secret
        key: api-key
  appKey: 
    valueFrom:
      secretKeyRef:
        name: datadog-secret
        key: app-key
  site: "app.datadoghq.com"

  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    containerCollectUsingVolumes: true

  apm:
    enabled: true 
    portEnabled: true
    env: "production"

  dogstatsd:
    enabled: true
    nonLocalTraffic: true
    port: 8125

  agent:
    env:
      - name: DD_REMOTE_CONFIGURATION_ENABLED
        value: "true"
      - name: DD_LOGS_INJECTION
        value: "true"
      - name: DD_APM_ENABLED
        value: "true"

  # containers:
  #   ports:
  #     - containerPort: 8126
  #       hostPort: 8126
  #       name: traceport
  #       protocol: TCP
  #     - containerPort: 8125
  #       hostPort: 8125
  #       name: dogstatsdport
  #       protocol: UDP
