datadog:
  apiKey: 
    valueFrom:
      secretKeyRef:
        name: datadog-secret
        key: api-key
  appKey: 
    valueFrom:
      secretKeyRef:
        name: datadog-secret
        key: app-key
  site: "app.datadoghq.com"

  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    containerCollectUsingVolumes: true

  apm:
    enabled: true 
    portEnabled: true
    env: "production"

  dogstatsd:
    enabled: true
    nonLocalTraffic: true

  agent:
    image:
      repository: "gcr.io/datadoghq/agent"
      tag: "7.31.1"
    env:
      - name: DD_LOGS_INJECTION
        value: "true"
      - name: DD_APM_ENABLED
        value: "true"
    volumeMounts:
      - name: datadog-config
        mountPath: /etc/datadog-agent/conf.d/python.d
    volumes:
      - name: datadog-config
        configMap:
          name: datadog-config

useHostPID: false
useHostNetwork: false
useHostPort: false
